-- ตารางบันทึกเลขมิเตอร์ไฟฟ้ารายห้องรายเดือน
--
-- เดิมหน้าบันทึกมิเตอร์เก็บค่าไว้ใน localStorage ของเบราว์เซอร์ ทำให้ข้อมูลหายเมื่อเปลี่ยนเครื่อง
-- ย้ายมาเก็บในฐานข้อมูลแทน โดยเก็บ "เลขมิเตอร์สะสม" ของเดือนนั้น
-- หน่วยที่ใช้จริงคือค่าของเดือนนี้ลบเดือนก่อน แล้วคิดเงินด้วย room.elec_rate

create table if not exists public.meter_reading (
  meter_id bigint generated by default as identity primary key,
  room_number character varying not null references public.room (room_number) on delete cascade,
  reading_month date not null,
  meter_reading integer not null default 0 check (meter_reading >= 0),
  created_at timestamptz not null default now(),
  constraint meter_reading_room_month_key unique (room_number, reading_month)
);

comment on table public.meter_reading is 'เลขมิเตอร์ไฟฟ้าสะสมของแต่ละห้อง แยกตามเดือน (เก็บเป็นวันที่ 1 ของเดือน)';

create index if not exists meter_reading_month_idx on public.meter_reading (reading_month);

alter table public.meter_reading enable row level security;

drop policy if exists "ดูมิเตอร์ได้" on public.meter_reading;
create policy "ดูมิเตอร์ได้" on public.meter_reading
  for select to authenticated
  using (room_number = public.current_room_number() or public.is_admin());

drop policy if exists "ผู้ดูแลจัดการมิเตอร์ได้" on public.meter_reading;
create policy "ผู้ดูแลจัดการมิเตอร์ได้" on public.meter_reading
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

grant select, insert, update, delete on public.meter_reading to authenticated;

revoke all on public.meter_reading from anon;